//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace schoolDbMvc.baza_con
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class COPI_15_12_16Entities3 : DbContext
    {
        public COPI_15_12_16Entities3()
            : base("name=COPI_15_12_16Entities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DIC_SUBJECTS> DIC_SUBJECTS { get; set; }
        public DbSet<TBL_ADMINS> TBL_ADMINS { get; set; }
        public DbSet<TBL_ASSESSMENTS> TBL_ASSESSMENTS { get; set; }
        public DbSet<TBL_CLASS> TBL_CLASS { get; set; }
        public DbSet<TBL_MODERATORS> TBL_MODERATORS { get; set; }
        public DbSet<TBL_STUDENS> TBL_STUDENS { get; set; }
        public DbSet<TBL_TEACHERS> TBL_TEACHERS { get; set; }
    }
}
